//GLSL version to use
#version 460 // there goes macos support :(, actually because this is vulkan, it miiiiight work on macos

//size of a workgroup for compute
layout (local_size_x = 1, local_size_y = 1) in;

//descriptor bindings for the pipeline
layout(rgba16f,set = 0, binding = 0) uniform image2D image;

layout (push_constant) uniform PushConstants {
    vec4 data1; // Color 1
    vec4 data2; // Color 2
};

void main()
{
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(image);

    // This is a gradient, it's a simple linear interpolation between two colors
    vec4 color = mix(data1, data2, float(texelCoord.x) / float(size.x));

    // Write the color to the image
    imageStore(image, texelCoord, color);
}
